spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ragdb
    username: raguser
    password: ragpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b
      embedding:
        options:
          model: nomic-embed-text:latest
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        max-document-batch-size: 10000
        dimensions: 768
        initialize-schema: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
server:
  port: 8050
